services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
      - SPRING_DATA_REDIS_HOST=redis
    depends_on:
      - redis

  recommend:
    build: ./outfit-recommend-server
    ports:
      - "8000:8000"
    depends_on:
      - app
