

cors:
  allowed-origin: https://outfitarchives.com

jwt:
  cookie-secure: true
  cookie-same-site: None

file:
  path-product: C:\jungseok\img\

ai:
  embedding:
    url: http://recommend:8000/embed
