spring:
  data:
    redis:
      host: localhost
      port: 6379

cors:
  allowed-origin: http://jungseok-outfit-frontend.s3-website.ap-northeast-2.amazonaws.com

jwt:
  cookie-secure: false

file:
  path-product: C:\jungseok\img\

ai:
  embedding:
    url: http://localhost:8000/embed
