spring:
  application:
    name: backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fasthub
    username: root
    password: 9401
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
jwt:
  access-expiration: 5400000
  refresh-expiration: 10800000  # 3hours * 60min * 60sec * 1000 millisecond
  access-secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  refresh-secret: VlwEyVBsYt9V7zq57TeasdfjasdfjascfPQye08f7MGVA9XkHa

file:
  path-product : C:\jungseok\img\

